meta_product_name: "VaporSooq"
meta_title: "VaporSooq - Jordanian Vape Online Market"
meta_description: "Jordan's First Online Vape Online Market"
meta_image: "VaporSooq(2).jpg"                       # should exist in `app/assets/images/`
